### PR TITLE
Added a new logo for EasyCrypto and Icons that can be used when GUI i…

### PR DESCRIPTION
**Pull request by smoberg**
#8 Adds a new logo for the EasyCrypto and Icons that can be used when GUI is implemented

### CODE REVIEW

**Comment by mbuet2ner** [comment]
Thank you @smoberg for your PR :fireworks: !
Could you please tell us what fonts were used for this logo? Would really like to see open source fonts to match our project :+1: .

**Comment by anttijuu** [comment]
That is a very good point. All elements of the project, including graphics, should and must follow the license of the project. If implementing a GUI, possible external graphics files there would have to be checked against their respective licenses too.

**Comment by smoberg** [comment]
The logo uses Ubuntu font which is an open source font that is under the Ubuntu Font license
Link for the font in google fonts: https://fonts.google.com/specimen/Ubuntu
License information: https://ubuntu.com/legal/font-licence

**Comment by mbuet2ner** [comment]
Thank you @smoberg for the clarification!
Unfortunately the license seems to be ambiguous at best, which led both the Fedora and Debian community to marking it as non-free.
See the [Wikipedia entry](https://en.wikipedia.org/wiki/Ubuntu_(typeface)#Ubuntu_Font_Licence) and the discussion in the [Debian project](https://bugs.launchpad.net/ubuntu-font-licence/+bug/769874) and the [Fedora project](https://bugzilla.redhat.com/show_bug.cgi?id=961642#c4). 

I think the OFL [license](https://en.wikipedia.org/wiki/SIL_Open_Font_License) is safe to use and there are some fonts listed [here](https://www.fontspace.com/category/ofl) that use this license. Otherwise Google provides some good open [fonts](https://fonts.google.com/) as well (not every font there might be truly open. Have not checked every single one). 

It would be great if you could update your logo with a free font :+1: , since the current one in use does not look good at all.

**Comment by smoberg** [comment]
Logo uses now Kanit https://fonts.google.com/specimen/Kanit which is under the OFL license you suggested @mbuet2ner.

**Comment by mbuet2ner** [comment]
Can you please make a new PR with the new logo? Just to be sure: I don't want to have the old logo with the problematic license in our history/ project. Thanks!

**Pull request closed without merging**
